site_name: neuralSPOT Edge
site_dir: "site"
site_url: "https://ambiqai.github.io/neuralspot-edge"
site_description: NeuralSPOT Edge, Keras addon targeted towards Ambiq edge SoCs
repo_name: AmbiqAI/neuralspot-edge
repo_url: https://github.com/AmbiqAI/neuralspot-edge
copyright: Copyright &copy; 2024 Ambiq

nav:
  - Home:
    - Home: index.md
    - Getting Started: usage/index.md
    - API Documentation: api/
    - Guides: guides/index.md
    - Examples: examples/index.md

  - Getting Started:
    - usage/index.md

  - API Documentation: api/

  - Guides:
    - guides/index.md

  - Examples:
    - examples/index.md

theme:
  name: material
  # favicon: assets/favicon.png
  # logo: assets/logo-white.png
  icon:
      repo: fontawesome/brands/github-alt
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Use system theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark theme
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.path

    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.expand  # navigation.expand or navigation.sections
    - content.tabs.link # all code tabs change simultaneously

plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          options:
            show_bases: false
            docstring_style: google
            docstring_section_style: list
            line_length: 120
            show_root_heading: false
            heading_level: 2
            merge_init_into_class: true
            show_root_full_path: false
            parameter_headings: true
            show_symbol_type_heading: true
            group_by_category: true
            show_category_heading: true
            modernize_annotations: true
            members_order: source
            filters: ["!^_", "^__init__$"]
            separate_signature: true
            show_signature: true
            show_signature_annotations: true
            show_docstring_attributes: true
            show_source: true

extra_css:
  - css/mkdocstrings.css
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - md_in_html
  - sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
